<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <EnableArkToolsCompliance>false</EnableArkToolsCompliance>
    <ArkToolsComplianceAnalyzerProject>true</ArkToolsComplianceAnalyzerProject>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="all" />
  </ItemGroup>
</Project>
