<Project>

	<Import Project="$(MSBuildThisFileDirectory)src/sdk/Ark.Tools.Sdk/Sdk/Sdk.targets" />

		
  <ItemGroup Label="Testing Platform Settings" Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.Analyzers" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup Label="Testing Platform Builder Hook" Condition="'$(IsTestProject)' == 'true'">
    <TestingPlatformBuilderHook Remove="031F8871-2660-4208-8F6B-FC142B40ABFF" />
    <TestingPlatformBuilderHook Include="031F8871-2660-4208-8F6B-FC142B40ABFF">
      <DisplayName>MSTest</DisplayName>
      <TypeFullName>Microsoft.VisualStudio.TestTools.UnitTesting.TestingPlatformBuilderHook</TypeFullName>
    </TestingPlatformBuilderHook>
  </ItemGroup>

</Project>
