// Evaluation PoC: Ark-owned incremental source generator = "GetTypesToRegister + RegisterDecorator at compile time".
// Answers review requirement: NO manual per-handler registration; every IQueryHandler<,> implementation in the
// compilation is discovered and its registration is emitted ALREADY WRAPPED in the full open-generic decorator chain.
// A newly added handler class is *guaranteed* decorated: the guarantee is structural (the generator closes each
// decorator over each discovered handler), not conventional.
//
// Also emits the mandatory conditional-fallback pattern statically:
//   - specific IValidator<T> implementations are registered;
//   - for every handler query without a specific validator, a closed NullValidator<Q> is emitted.
// Output is plain constructor calls: zero reflection, zero MakeGenericType => NativeAOT/trim clean by construction.

using Microsoft.CodeAnalysis;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HandlerGen.Generator
{
    [Generator]
    public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
    {
        // ponytail: type names hardcoded to the evaluation namespace; a production generator would
        // locate the Ark.Tools.Solid abstractions by metadata name from the referenced package.
        private const string _ns = "HandlerGen.Evaluation";
        private static readonly SymbolDisplayFormat _fqn = SymbolDisplayFormat.FullyQualifiedFormat;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ponytail: CompilationProvider = full re-scan per keystroke; production would use ForAttributeWithMetadataName
            // and a syntax provider keyed on base-lists for incrementality.
            context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
            {
                var handlerIface = compilation.GetTypeByMetadataName(_ns + ".IQueryHandler`2");
                var validatorIface = compilation.GetTypeByMetadataName(_ns + ".IValidator`1");
                var nullValidator = compilation.GetTypeByMetadataName(_ns + ".NullValidator`1");
                var decoratorAttr = compilation.GetTypeByMetadataName(_ns + ".HandlerDecoratorAttribute");
                if (handlerIface is null || validatorIface is null || nullValidator is null || decoratorAttr is null)
                    return;

                var allTypes = _allTypes(compilation.Assembly.GlobalNamespace).ToList();

                // handlers: concrete, non-generic classes implementing IQueryHandler<Q,R>
                var handlers = allTypes
                    .Where(t => t.TypeKind == TypeKind.Class && !t.IsAbstract && !t.IsGenericType)
                    .SelectMany(t => t.AllInterfaces
                        .Where(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, handlerIface))
                        .Select(i => (Impl: t, Query: i.TypeArguments[0], Result: i.TypeArguments[1])))
                    .OrderBy(h => h.Impl.Name, StringComparer.Ordinal)
                    .ToList();

                // decorators: open-generic arity-2 classes marked [HandlerDecorator(order)]
                var decorators = allTypes
                    .Where(t => t.TypeKind == TypeKind.Class && t.IsGenericType && t.Arity == 2)
                    .Select(t => (Impl: t, Attr: t.GetAttributes().FirstOrDefault(a =>
                        SymbolEqualityComparer.Default.Equals(a.AttributeClass, decoratorAttr))))
                    .Where(t => t.Attr is not null)
                    .Select(t => (t.Impl, Order: (int)t.Attr!.ConstructorArguments[0].Value!))
                    .OrderBy(t => t.Order) // innermost first
                    .ToList();

                // specific validators: concrete non-generic classes implementing IValidator<T>
                var validators = allTypes
                    .Where(t => t.TypeKind == TypeKind.Class && !t.IsAbstract && !t.IsGenericType)
                    .SelectMany(t => t.AllInterfaces
                        .Where(i => SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, validatorIface))
                        .Select(i => (Impl: t, Subject: i.TypeArguments[0])))
                    .ToList();

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated by HandlerGen.Generator/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("namespace " + _ns);
                sb.AppendLine("{");
                sb.AppendLine("    public static class GeneratedHandlerRegistrations");
                sb.AppendLine("    {");

                // manifest: lets the app assert the "every handler is registered+decorated" guarantee
                sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyList<(global::System.Type Query, global::System.Type Result, global::System.Type Handler)> KnownHandlers = new (global::System.Type, global::System.Type, global::System.Type)[]");
                sb.AppendLine("        {");
                foreach (var h in handlers)
                    sb.AppendLine($"            (typeof({h.Query.ToDisplayString(_fqn)}), typeof({h.Result.ToDisplayString(_fqn)}), typeof({h.Impl.ToDisplayString(_fqn)})),");
                sb.AppendLine("        };");
                sb.AppendLine();

                // dispatch map: query type -> closed handler service type; replaces the mediator's
                // MakeGenericType call (IL3050) with a warning-free static lookup
                sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Type> HandlerServiceByQuery = new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type>");
                sb.AppendLine("        {");
                foreach (var h in handlers)
                    sb.AppendLine($"            [typeof({h.Query.ToDisplayString(_fqn)})] = typeof({handlerIface.Construct((INamedTypeSymbol)h.Query, (INamedTypeSymbol)h.Result).ToDisplayString(_fqn)}),");
                sb.AppendLine("        };");
                sb.AppendLine();
                sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDiscoveredHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
                sb.AppendLine("        {");

                // (a) specific validators, then closed fallbacks (RegisterConditional equivalent, resolved at compile time)
                var covered = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var v in validators)
                {
                    covered.Add(v.Subject);
                    sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{validatorIface.Construct((INamedTypeSymbol)v.Subject).ToDisplayString(_fqn)}, {v.Impl.ToDisplayString(_fqn)}>(services);");
                }
                foreach (var q in handlers.Select(h => h.Query).Distinct(SymbolEqualityComparer.Default).Cast<ITypeSymbol>())
                {
                    if (covered.Contains(q)) continue;
                    sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{validatorIface.Construct((INamedTypeSymbol)q).ToDisplayString(_fqn)}, {nullValidator.Construct((INamedTypeSymbol)q).ToDisplayString(_fqn)}>(services);");
                }

                // (b) handlers, each wrapped in EVERY registered decorator (open-generic decoration, closed at compile time)
                foreach (var h in handlers)
                {
                    var service = handlerIface.Construct((INamedTypeSymbol)h.Query, (INamedTypeSymbol)h.Result).ToDisplayString(_fqn);
                    var expr = _newExpr(h.Impl, inner: null, service);
                    foreach (var d in decorators)
                        expr = _newExpr(d.Impl.Construct((INamedTypeSymbol)h.Query, (INamedTypeSymbol)h.Result), expr, service);
                    sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<{service}>(services, sp => {expr});");
                }

                sb.AppendLine("            return services;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                spc.AddSource("GeneratedHandlerRegistrations.g.cs", sb.ToString());
            });
        }

        // builds `new T(arg, arg, ...)`: the inner-handler ctor parameter receives `inner`,
        // every other dependency is a statically-typed sp.GetRequiredService<T>() call
        private static string _newExpr(INamedTypeSymbol type, string? inner, string serviceFqn)
        {
            var ctor = type.InstanceConstructors
                .Where(c => c.DeclaredAccessibility == Accessibility.Public)
                .OrderByDescending(c => c.Parameters.Length)
                .First();
            var args = ctor.Parameters.Select(p =>
                inner is not null && p.Type.ToDisplayString(_fqn) == serviceFqn
                    ? inner
                    : $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{p.Type.ToDisplayString(_fqn)}>(sp)");
            return $"new {type.ToDisplayString(_fqn)}({string.Join(", ", args)})";
        }

        private static IEnumerable<INamedTypeSymbol> _allTypes(INamespaceSymbol ns)
        {
            foreach (var m in ns.GetMembers())
            {
                if (m is INamespaceSymbol child)
                    foreach (var t in _allTypes(child)) yield return t;
                else if (m is INamedTypeSymbol t)
                    yield return t;
            }
        }
    }
}
