name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - develop
    - master
# Change Paths below as needed (cannot use variable!)
  paths:
    include:
    - Core/*
    - Ark.Reference.Common/*

variables:
  workingDirectory: '$(Build.SourcesDirectory)'
  vmImageName: 'ubuntu-latest'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    BuildConfiguration: 'release'
  ${{ if not(eq(variables['Build.SourceBranchName'], 'master')) }}:
    BuildConfiguration: 'debug'
  BuildPlatform: 'any cpu'
  projectName: 'Ark.ReferenceProject'
  service: 'Core'
  devEnvironment: 'Ark-Reference-Dev'
  devResourceGroup: 'Ark-Reference-Shared'
  devSubscription: 'Ark'
  devDeploymentNamePrefix: 'Ark-Reference'
  
stages:
    - stage: Build_Stage
      displayName: Build stage
      variables:
        solutionPath: '${{ variables.projectName }}.sln'
        webInterfaceProject: '${{ variables.projectName }}.${{ variables.service }}.WebInterface'
        databaseProject: '${{ variables.projectName }}.${{ variables.service }}.Database'
        servicePath: '$(Build.SourcesDirectory)/${{ variables.service }}'
      jobs:
      - job: BuildJob
        timeoutInMinutes: 60 # how long to run the job before automatically cancelling
        cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
        pool:
          vmImage: $(vmImageName)
          demands:
          - msbuild
          - visualstudio
          - vstest
        variables:
          NUGET_PACKAGES: $(Build.SourcesDirectory)/.nuget/packages
        steps:
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet 6.x'
          inputs:
            versionSpec: 6.x
        - task: UseDotNet@2
          displayName: 'Use .Net Core sdk'
          inputs:
            useGlobalJson: true

        - task: Cache@2
          displayName: Cache NuGet
          inputs:
            key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!/bin/**,!**/obj/**'
            path: '$(NUGET_PACKAGES)'
            restoreKeys: |
              nuget | "$(Agent.OS)"
              nuget
            cacheHitVar: 'CACHE_RESTORED'

        - task: NuGetCommand@2
          condition: ne(variables.CACHE_RESTORED, true)
          displayName: 'NuGet restore'
          inputs:
            command: 'restore'
            restoreSolution: ${{ variables.solutionPath }}

        - task: VSBuild@1
          displayName: 'Build solution'
          inputs:
            solution: ${{ variables.solutionPath }}
            vsVersion: '17.0'
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
            clean: true
            maximumCpuCount: true

        - task: VSBuild@1
          displayName: 'Build solution again (for dacpac)'
          inputs:
            solution: ${{ variables.solutionPath }}
            vsVersion: '17.0'
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
            maximumCpuCount: true

        - task: VisualStudioTestPlatformInstaller@1
          inputs:
            packageFeedSelector: 'nugetOrg' # Options: nugetOrg, customFeed, netShare
            versionSelector: 'latestStable' # Required when packageFeedSelector == NugetOrg || PackageFeedSelector == CustomFeed# Options: latestPreRelease, latestStable, specificVersion
      
        - task: VSTest@2
          displayName: 'VsTest - testAssemblies'
          condition: and(succeeded(), not(or(contains(variables['Build.SourceVersionMessage'], '[SkipTests]'), contains(variables['OverrideField'], '[SkipTests]'), contains(variables['Build.SourceVersionMessage'], 'hotfix/'))))
          inputs:
            testAssemblyVer2: |
             **/*.Tests/**/$(BuildConfiguration)/**/*.Tests.dll
             **/*.UnitTests/**/$(BuildConfiguration)/**/*.UnitTests.dll
             !**/obj/**
             !**/ref/**
            searchFolder: '$(build.sourcesdirectory)/Core'
            runSettingsFile: CodeCoverage.runsettings
            codeCoverageEnabled: true
            diagnosticsEnabled: true

        - task: CopyFiles@2
          displayName: 'Copy SQL Files'
          inputs:
            SourceFolder: '$(build.sourcesdirectory)/${{ variables.service }}/${{ variables.databaseProject }}'
            Contents: |
             **/*.dacpac
             **/*.publish.xml
             **/_Migrations\*.sql
            TargetFolder: '$(build.artifactstagingdirectory)/${{ variables.service }}/${{ variables.databaseProject }}'
            flattenFolders: true

        - task: DotNetCoreCLI@2
          displayName: 'dotnet publish'
          inputs:
            command: publish
            publishWebProjects: false
            projects: '$(build.sourcesdirectory)/${{ variables.service }}/${{ variables.webInterfaceProject }}/${{ variables.webInterfaceProject }}.csproj'
            arguments: '-o "$(build.artifactstagingdirectory)/${{ variables.service }}/${{ variables.webInterfaceProject }}" --framework "net8.0" --configuration $(BuildConfiguration) --no-build'

        - task: PublishSymbols@2
          displayName: 'Publish symbols path'
          inputs:
            SymbolServerType: TeamServices

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'

    - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature')) }}:
      - stage: DevEnv_Stage
        displayName: Dev Deploy ${{ variables.projectName }}
        dependsOn: Build_Stage
        variables:
          webInterfaceProject: '${{ variables.projectName }}.${{ variables.service }}.WebInterface'
          databaseProject: '${{ variables.projectName }}.${{ variables.service }}.Database'
        jobs:
        - deployment: DevEnv_Deploy
          displayName: Dev Deploy ${{ variables.projectName }}
          environment: ${{ variables.devEnvironment }}
          variables:
            resourceGroup: ${{ variables.devResourceGroup }}
            subscription: ${{ variables.devSubscription }}
            deploymentNamePrefix: ${{ variables.deploymentNamePrefix }}
          pool:
            vmImage: $(vmImageName)
            #name: $(vmPoolName)
          strategy:
            runOnce:
              deploy:
                steps:
                - task: ARM Outputs@6
                  displayName: 'ARM Outputs'
                  inputs:
                    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
                    ConnectedServiceNameARM: '${{ variables.subscription }}'
                    resourceGroupName: $(resourceGroup)
                    prefix: 'arm.'
                    whenLastDeploymentIsFailed: 'latestSuccesful'
                    deploymentNameFilter: '${{ variables.deploymentNamePrefix }}*'
                - task: AzureAppServiceManage@0
                  displayName: 'Stop Azure App Service: $(arm.CoreService)'
                  inputs:
                    azureSubscription: '${{ variables.subscription }}'
                    Action: 'Stop Azure App Service'
                    WebAppName: '$(arm.coreService)'
                - task: SqlAzureDacpacDeployment@1
                  displayName: 'Pre Migrations'
                  inputs:
                    azureSubscription: '${{ variables.subscription }}'
                    ServerName: '$(arm.serverFQDN)'
                    DatabaseName: '$(arm.coredb)'
                    SqlUsername: '$(arm.adminUsername)'
                    SqlPassword: '$(arm.adminPassword)'
                    deployType: SqlTask
                    SqlFile: '$(Pipeline.Workspace)/drop/${{ variables.service }}/${{ variables.databaseProject }}/RunMigration.PreDeployment.sql'
                    SqlAdditionalArguments: '-Variable "MyPath = $(Pipeline.Workspace)/drop/${{ variables.service }}/${{ variables.databaseProject }}/" -QueryTimeout 360'
                - task: SqlAzureDacpacDeployment@1
                  displayName: DacPac
                  inputs:
                    azureSubscription: '${{ variables.subscription }}'
                    ServerName: '$(arm.serverFQDN)'
                    DatabaseName: '$(arm.coredb)'
                    SqlUsername: '$(arm.adminUsername)'
                    SqlPassword: '$(arm.adminPassword)'
                    DacpacFile: '$(Pipeline.Workspace)/drop/${{ variables.service }}/${{ variables.databaseProject }}/${{ variables.databaseProject }}.dacpac'
                    PublishProfile: '$(Pipeline.Workspace)/drop/${{ variables.service }}/${{ variables.databaseProject }}/${{ variables.databaseProject }}.publish.xml'
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Azure App Service Deploy: $(arm.coreService)'
                  inputs:
                    azureSubscription: '${{ variables.subscription }}'
                    WebAppName: '$(arm.coreService)'
                    packageForLinux: '$(Pipeline.Workspace)/drop/${{ variables.service }}/${{ variables.webInterfaceProject }}/${{variables.webInterfaceProject }}.zip'
                    enableCustomDeployment: true
                    DeploymentType: zipDeploy
                - task: AzureAppServiceManage@0
                  displayName: 'Start Azure App Service: $(arm.coreService)'
                  inputs:
                    azureSubscription: '${{ variables.subscription }}'
                    Action: 'Start Azure App Service'
                    WebAppName: '$(arm.coreService)'
                - task: OneLuckiDev.release-web-smoke-test-task.vsts-release-web-test.oneluckidevWebSmokeTest@1
                  displayName: 'Web Smoke Test'
                  inputs:
                    url: 'https://$(arm.coreService).azurewebsites.net/swagger'
                    retryAttemptCount: 10
                    retryDelay: 5000
