// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ark.MediatorFramework.MessagingGenerators;

/// <summary>Emits participant-owned identity constants and the participant's messaging contract registry core.</summary>
/// <remarks>
/// The mapping depends only on the participant declaration, so it is generated into the participant's
/// public partial class in the contracts (non-Host) assembly: a static <c>typeof(T)</c> to current-name
/// lookup for writes and a <c>switch</c> name to typed-deserializer dispatch for reads, without
/// reflection or CLR type loading. Generation is skipped when the participant is not declared
/// <c>partial</c>.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class MessagingParticipantGenerator : IIncrementalGenerator
{
    private const string _participantAttribute = "Ark.MediatorFramework.MessagingParticipantAttribute";
    private const string _messageAttribute = "Ark.MediatorFramework.MessageAttribute";
    private const string _eventAttribute = "Ark.MediatorFramework.EventAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var participants = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _participantAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(participants, static (productionContext, symbol) =>
            _emit(productionContext, symbol));
    }

    private static void _emit(SourceProductionContext context, INamedTypeSymbol symbol)
    {
        if (!_isPartial(symbol))
            return;

        var attribute = symbol.GetAttributes().First(attribute =>
            attribute.AttributeClass?.ToDisplayString() == _participantAttribute);
        var identity = _string(attribute, "Identity")
            ?? MessagingMetadata.NormalizeParticipantIdentity(symbol.Name);

        var contracts = _types(attribute, "Processes")
            .Concat(_types(attribute, "Publishes"))
            .Concat(_types(attribute, "Subscribes"))
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .OrderBy(contract => MessagingMetadata.ContractName(contract), StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine();
        _appendNamespaceOpen(source, symbol);
        _appendParticipantOpen(source, string.Empty, symbol);
        const string indent = "    ";

        source.Append(indent).Append("/// <summary>The participant identity used for the sender-identity and queue naming headers.</summary>").AppendLine()
            .Append(indent).Append("public const string Identity = \"").Append(_escape(identity)).AppendLine("\";")
            .AppendLine();

        _appendRegistryCore(source, indent, symbol, contracts);

        _appendParticipantClose(source);
        context.AddSource(_hintName(symbol), source.ToString());
    }

    private static void _appendRegistryCore(
        StringBuilder source,
        string indent,
        INamedTypeSymbol participant,
        IReadOnlyList<INamedTypeSymbol> contracts)
    {
        source.Append(indent).Append("/// <summary>Maps a statically registered contract type to its logical wire name for writes.</summary>").AppendLine()
            .Append(indent).AppendLine("public static bool TryGetContractName(global::System.Type contractType, out string name)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (contractType is null)")
            .Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(contractType));");
        foreach (var contract in contracts)
        {
            source.Append(indent).Append("    if (contractType == typeof(")
                .Append(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                .AppendLine("))")
                .Append(indent).AppendLine("    {");
            source.Append(indent).Append("        name = \"").Append(_escape(MessagingMetadata.ContractName(contract))).AppendLine("\";")
                .Append(indent).AppendLine("        return true;")
                .Append(indent).AppendLine("    }");
        }
        source.Append(indent).AppendLine("    name = string.Empty;")
            .Append(indent).AppendLine("    return false;")
            .Append(indent).AppendLine("}")
            .AppendLine();

        source.Append(indent).Append("/// <summary>Deserializes a transport-owned body using the contract selected by its wire name (current name or former-name alias).</summary>").AppendLine()
            .Append(indent).AppendLine("public static object DeserializeContract(")
            .Append(indent).AppendLine("    string name,")
            .Append(indent).AppendLine("    in global::System.Buffers.ReadOnlySequence<byte> payload,")
            .Append(indent).AppendLine("    Ark.MediatorFramework.Messaging.IMessagingCodec codec)")
            .Append(indent).AppendLine("{")
            .Append(indent).AppendLine("    if (string.IsNullOrEmpty(name))")
            .Append(indent).AppendLine("        throw new global::System.ArgumentException(\"The contract name must not be null or empty.\", nameof(name));")
            .Append(indent).AppendLine("    if (codec is null)")
            .Append(indent).AppendLine("        throw new global::System.ArgumentNullException(nameof(codec));")
            .Append(indent).AppendLine("    switch (name)")
            .Append(indent).AppendLine("    {");
        foreach (var contract in contracts)
        {
            var qualifiedType = contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var names = _contractNames(contract);
            foreach (var name in names)
                source.Append(indent).Append("        case \"").Append(_escape(name)).AppendLine("\":");
            source.Append(indent).Append("            return codec.Deserialize<")
                .Append(qualifiedType)
                .AppendLine(">(payload);");
        }
        source.Append(indent).AppendLine("        default:")
            .Append(indent).Append("            throw new Ark.MediatorFramework.Messaging.MessagingProtocolException(")
            .AppendLine()
            .Append(indent).AppendLine("                Ark.MediatorFramework.Messaging.MessagingFailureKind.UnknownContract,")
            .Append(indent).Append("                \"The message contract is not registered on participant '")
            .Append(participant.Name)
            .AppendLine("'.\",")
            .Append(indent).AppendLine("                Ark.MediatorFramework.Messaging.MessagingHeaderNames.MessageType);")
            .Append(indent).AppendLine("    }")
            .Append(indent).AppendLine("}");
    }

    private static ImmutableArray<string> _contractNames(INamedTypeSymbol contract)
    {
        var attribute = contract.GetAttributes().FirstOrDefault(item =>
            item.AttributeClass?.ToDisplayString() is _messageAttribute or _eventAttribute);
        var names = ImmutableArray.CreateBuilder<string>();
        names.Add(MessagingMetadata.ContractName(contract));
        if (attribute is not null)
        {
            var formerNames = _named(attribute, "FormerNames");
            if (formerNames.Kind == TypedConstantKind.Array)
            {
                foreach (var name in formerNames.Values.Where(item => item.Value is string).Select(item => (string)item.Value!))
                {
                    if (!names.Contains(name, StringComparer.Ordinal))
                        names.Add(name);
                }
            }
        }
        return names.ToImmutable();
    }

#pragma warning disable MA0045 // GetSyntax: cancellation-free symbol inspection matches MessagingNetworkGenerator
    private static bool _isPartial(INamedTypeSymbol symbol)
    {
        foreach (var syntaxReference in symbol.DeclaringSyntaxReferences)
        {
            if (syntaxReference.GetSyntax() is ClassDeclarationSyntax declaration
                && declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                return true;
        }
        return false;
    }
#pragma warning restore MA0045

    private static void _appendNamespaceOpen(StringBuilder source, INamedTypeSymbol symbol)
    {
        if (symbol.ContainingNamespace is null || symbol.ContainingNamespace.IsGlobalNamespace)
            return;
        source.Append("namespace ").Append(symbol.ContainingNamespace.ToDisplayString()).AppendLine(";")
            .AppendLine();
    }

    private static void _appendParticipantOpen(StringBuilder source, string indent, INamedTypeSymbol symbol)
    {
        var typeParameters = symbol.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", symbol.TypeParameters.Select(parameter => parameter.Name)) + ">";
        source.Append(indent).Append("partial class ").Append(symbol.Name).Append(typeParameters).AppendLine()
            .Append(indent).AppendLine("{");
    }

    private static void _appendParticipantClose(StringBuilder source)
    {
        source.AppendLine("}");
    }

    private static string _hintName(INamedTypeSymbol symbol)
    {
        var builder = new StringBuilder();
        foreach (var character in symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat))
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        builder.Append("_MessagingContracts.g.cs");
        return builder.ToString();
    }

    private static string _escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static ImmutableArray<INamedTypeSymbol> _types(AttributeData attribute, string name)
    {
        var value = _named(attribute, name);
        if (value.Kind != TypedConstantKind.Array)
            return ImmutableArray<INamedTypeSymbol>.Empty;
        return value.Values
            .Where(item => item.Value is INamedTypeSymbol)
            .Select(item => (INamedTypeSymbol)item.Value!)
            .ToImmutableArray();
    }

    private static string? _string(AttributeData attribute, string name)
    {
        return _named(attribute, name).Value as string;
    }

    private static TypedConstant _named(AttributeData attribute, string name)
    {
        foreach (var argument in attribute.NamedArguments)
        {
            if (argument.Key == name)
                return argument.Value;
        }
        return default;
    }
}
