<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <FunctionsInDependencies>true</FunctionsInDependencies>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk"
                      OutputItemType="Analyzer"
                      PrivateAssets="all" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Ark.Tools.AspNetCore.ApplicationInsights" />
    <PackageReference Include="Ark.Tools.MediatorFramework.AzureFunctions" />
    <PackageReference Include="Ark.Tools.MediatorFramework.Rebus" />
    <PackageReference Include="Ark.Tools.Rebus" />
    <PackageReference Include="Ark.Tools.AspNetCore.HealthChecks" />
    <PackageReference Include="Ark.Tools.NLog.Configuration" />
    <ProjectReference Include="../../../../src/mediator-framework/Ark.Tools.MediatorFramework.AzureFunctions.Generators/Ark.Tools.MediatorFramework.AzureFunctions.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Ark.MediatorFramework.Sample.RebusProcessor\Ark.MediatorFramework.Sample.RebusProcessor.csproj" />
    <ProjectReference Include="..\Ark.MediatorFramework.Sample.Functions\Ark.MediatorFramework.Sample.Functions.csproj" />
  </ItemGroup>

</Project>
