<Project>
	  <!-- Remove this on eject -->
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>6.6.6</Version>
    <ArkExportProtoDir>$(MSBuildThisFileDirectory)src/Ark.MediatorFramework.Sample.WebInterface/proto</ArkExportProtoDir>
  </PropertyGroup>


  <PropertyGroup Label="Common Build Settings">
		<NoWarn>$(NoWarn);CS1591</NoWarn>
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>

    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>

  </PropertyGroup>

  <PropertyGroup Label="NuGet Audit">
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1901;NU1905;</WarningsNotAsErrors>
  </PropertyGroup>


  <PropertyGroup Label="Test Settings" Condition="'$(IsTestProject)' == 'true'">
    <OutputType>Exe</OutputType>
    <EnableMSTestRunner>true</EnableMSTestRunner>
  </PropertyGroup>


</Project>
