<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="../../src/common/Ark.Tools.Core.Analyzers/Ark.Tools.Core.Analyzers.csproj" />
  </ItemGroup>
</Project>
