<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- the other props are defined in Directory.Build.props -->
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Description>OpenTelemetry and Azure Monitor Distro setup for Ark ASP.NET Core hosts.</Description>
    <PackageTags>Ark;C#;.NET;Framework;AspNetCore;OpenTelemetry;AzureMonitor</PackageTags>
    <Version>$(AspNetCoreGroupVersion)</Version>
    <VersionSuffix>$(AspNetCoreGroupVersionSuffix)</VersionSuffix>
    <Version Condition="'$(VersionSuffix)' != ''">$(Version)-$(VersionSuffix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\common\Ark.Tools.Rebus\Ark.Tools.Rebus.csproj" />
    <ProjectReference Include="..\..\common\Ark.Tools.OTel\Ark.Tools.OTel.csproj" />
    <ProjectReference Include="..\Ark.Tools.AspNetCore\Ark.Tools.AspNetCore.csproj" />
  </ItemGroup>
</Project>
