<Project>
  <PropertyGroup Condition="'$(ArkApiSurfaceEnabled)' != 'false'">
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath Condition="'$(CompilerGeneratedFilesOutputPath)' == ''">$(MSBuildProjectDirectory)/obj/$(Configuration)/$(TargetFramework)/generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
</Project>
