<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ark.Tools.Rebus" />
    <PackageReference Include="Ark.Tools.Solid.SimpleInjector" />
    <PackageReference Include="Ark.Tools.MediatorFramework.Messaging.Azure" />
    <PackageReference Include="Ark.Tools.MediatorFramework.AzureFunctions.SimpleInjector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ark.MediatorFramework.Sample.AzureFunctions\Ark.MediatorFramework.Sample.AzureFunctions.csproj" />
    <ProjectReference Include="..\..\src\Ark.MediatorFramework.Sample.AuditFunctions\Ark.MediatorFramework.Sample.AuditFunctions.csproj">
      <Aliases>AuditFunctions</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\Core\Ark.MediatorFramework.Sample.Core.API\Ark.MediatorFramework.Sample.Core.API.csproj" />
  </ItemGroup>

</Project>
