<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks></TargetFrameworks>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ArkExportProto>false</ArkExportProto>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <ProjectReference Include="../../src/mediator-framework/Ark.Tools.MediatorFramework.Grpc/Ark.Tools.MediatorFramework.Grpc.csproj" />
    <ProjectReference Include="../../src/common/Ark.Tools.Nodatime.Protobuf/Ark.Tools.Nodatime.Protobuf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Ark.Tools.MediatorFramework.Hosting.Contracts/Ark.Tools.MediatorFramework.Hosting.Contracts.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="IncludeHostingProto" BeforeTargets="Protobuf_BeforeCompile">
    <ItemGroup>
      <Protobuf Include="../Ark.Tools.MediatorFramework.Hosting.Contracts/obj/$(Configuration)/net10.0/ark-proto/Hosting.proto"
                GrpcServices="Client"
                Link="Hosting.proto"
                AdditionalImportDirs="$(NuGetPackageRoot)/google.api.commonprotos/2.17.0/content/protos;../Ark.Tools.MediatorFramework.Hosting.Contracts/obj/$(Configuration)/net10.0/ark-proto" />
    </ItemGroup>
  </Target>

</Project>
