<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Description>Azure Service Bus, Storage Queue, and Blob DataBus integrations for MediatorFramework messaging</Description>
    <PackageTags>Ark;C#;.NET;Framework;Mediator;Messaging;Azure</PackageTags>
    <Version>$(ArkToolsCoreVersion)</Version>
    <VersionSuffix>$(ArkToolsCoreVersionSuffix)</VersionSuffix>
    <Version Condition="'$(VersionSuffix)' != ''">$(Version)-$(VersionSuffix)</Version>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Queues" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <ProjectReference Include="..\Ark.Tools.MediatorFramework.Messaging\Ark.Tools.MediatorFramework.Messaging.csproj" />
  </ItemGroup>
</Project>
