// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System.Collections.Immutable;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Ark.MediatorFramework.Generators
{
    /// <summary>
    /// Incremental generator that discovers pure <c>Ark.Tools.Solid</c> requests/queries
    /// decorated with <c>[ArkEndpoint]</c> and emits the transport hosting code
    /// (ASP.NET Core Minimal API mappings and Rebus message-handler wrappers) at compile time.
    /// This removes the MVC runtime-reflection tax while keeping handlers transport-agnostic.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class ArkEndpointGenerator : IIncrementalGenerator
    {
        private const string EndpointAttribute = "Ark.MediatorFramework.ArkEndpointAttribute";
        private const string RequestInterface = "Ark.Tools.Solid.IRequest`1";
        private const string QueryInterface = "Ark.Tools.Solid.IQuery`1";

        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var endpoints = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    EndpointAttribute,
                    predicate: static (node, _) => node is TypeDeclarationSyntax,
                    transform: static (ctx, _) => Extract(ctx))
                .Where(static e => e is not null)
                .Select(static (e, _) => e!.Value);

            var collected = endpoints.Collect();

            context.RegisterSourceOutput(collected, static (spc, items) => Emit(spc, items));
        }

        private static EndpointModel? Extract(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol type)
                return null;

            var attr = ctx.Attributes[0];
            if (attr.ConstructorArguments.Length != 2)
                return null;

            var verb = attr.ConstructorArguments[0].Value as string;
            var template = attr.ConstructorArguments[1].Value as string;
            if (string.IsNullOrWhiteSpace(verb) || string.IsNullOrWhiteSpace(template))
                return null;

            string? response = null;
            var kind = HandlerKind.None;

            foreach (var iface in type.AllInterfaces)
            {
                var def = iface.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (def == "global::Ark.Tools.Solid.IRequest<TResponse>")
                {
                    kind = HandlerKind.Request;
                    response = iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    break;
                }

                if (def == "global::Ark.Tools.Solid.IQuery<TResult>")
                {
                    kind = HandlerKind.Query;
                    response = iface.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    break;
                }
            }

            if (kind == HandlerKind.None || response is null)
                return null;

            return new EndpointModel(
                type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                type.Name,
                verb!.ToUpperInvariant(),
                template!,
                response,
                kind);
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<EndpointModel> items)
        {
            if (items.IsDefaultOrEmpty)
                return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace Ark.MediatorFramework.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Source-generated transport hosting for pure Ark.Tools.Solid handlers.</summary>");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Ark.MediatorFramework.Generators\", \"1.0.0\")]");
            sb.AppendLine("    public static class ArkGeneratedEndpoints");
            sb.AppendLine("    {");

            // Minimal API registration.
            sb.AppendLine("        /// <summary>Maps every discovered handler to a Minimal API endpoint.</summary>");
            sb.AppendLine("        public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapArkEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
            sb.AppendLine("        {");
            foreach (var e in items)
            {
                var map = MapMethod(e.Verb);
                var handlerService = e.Kind == HandlerKind.Query
                    ? "global::Ark.Tools.Solid.IQueryHandler<" + e.TypeFullName + ", " + e.Response + ">"
                    : "global::Ark.Tools.Solid.IRequestHandler<" + e.TypeFullName + ", " + e.Response + ">";
                var bind = e.Verb == "GET" || e.Verb == "DELETE"
                    ? "[global::Microsoft.AspNetCore.Http.AsParameters] "
                    : string.Empty;

                sb.AppendLine("            app." + map + "(" + Literal(e.Template) + ", static async (");
                sb.AppendLine("                " + bind + e.TypeFullName + " request,");
                sb.AppendLine("                global::Microsoft.AspNetCore.Http.HttpContext httpContext,");
                sb.AppendLine("                global::System.Threading.CancellationToken cancellationToken) =>");
                sb.AppendLine("            {");
                sb.AppendLine("                var container = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::SimpleInjector.Container>(httpContext.RequestServices);");
                sb.AppendLine("                await using var scope = global::SimpleInjector.Lifestyles.AsyncScopedLifestyle.BeginScope(container);");
                sb.AppendLine("                var handler = container.GetInstance<" + handlerService + ">();");
                sb.AppendLine("                var result = await handler.ExecuteAsync(request, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("                return global::Microsoft.AspNetCore.Http.Results.Ok(result);");
                sb.AppendLine("            });");
            }
            sb.AppendLine("            return app;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Rebus handler registration (requests only; queries are reads).
            sb.AppendLine("        /// <summary>Registers the generated Rebus handler wrappers into the SimpleInjector collection resolved by the Rebus activator.</summary>");
            sb.AppendLine("        public static void RegisterArkRebusHandlers(global::SimpleInjector.Container container)");
            sb.AppendLine("        {");
            foreach (var e in items.Where(static x => x.Kind == HandlerKind.Request))
            {
                sb.AppendLine("            container.Collection.Append(typeof(global::Rebus.Handlers.IHandleMessages<" + e.TypeFullName + ">), typeof(" + e.TypeName + "RebusHandler));");
            }
            sb.AppendLine("        }");

            // Generated Rebus wrappers.
            foreach (var e in items.Where(static x => x.Kind == HandlerKind.Request))
            {
                var handlerService = "global::Ark.Tools.Solid.IRequestHandler<" + e.TypeFullName + ", " + e.Response + ">";
                sb.AppendLine();
                sb.AppendLine("        /// <summary>Generated Rebus wrapper dispatching to the pure handler for <c>" + e.TypeName + "</c>.</summary>");
                sb.AppendLine("        [global::System.CodeDom.Compiler.GeneratedCode(\"Ark.MediatorFramework.Generators\", \"1.0.0\")]");
                sb.AppendLine("        public sealed class " + e.TypeName + "RebusHandler : global::Rebus.Handlers.IHandleMessages<" + e.TypeFullName + ">");
                sb.AppendLine("        {");
                sb.AppendLine("            private readonly " + handlerService + " _handler;");
                sb.AppendLine("            /// <summary>Initializes a new instance.</summary>");
                sb.AppendLine("            public " + e.TypeName + "RebusHandler(" + handlerService + " handler) { _handler = handler; }");
                sb.AppendLine("            /// <inheritdoc />");
                sb.AppendLine("            public async global::System.Threading.Tasks.Task Handle(" + e.TypeFullName + " message)");
                sb.AppendLine("                => await _handler.ExecuteAsync(message).ConfigureAwait(false);");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("ArkGeneratedEndpoints.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string MapMethod(string verb) => verb switch
        {
            "GET" => "MapGet",
            "POST" => "MapPost",
            "PUT" => "MapPut",
            "DELETE" => "MapDelete",
            "PATCH" => "MapPatch",
            _ => "MapPost",
        };

        private static string Literal(string value)
            => SyntaxFactory.Literal(value).ToFullString();

        private enum HandlerKind
        {
            None = 0,
            Request = 1,
            Query = 2,
        }

        private readonly struct EndpointModel
        {
            public EndpointModel(string typeFullName, string typeName, string verb, string template, string response, HandlerKind kind)
            {
                TypeFullName = typeFullName;
                TypeName = typeName;
                Verb = verb;
                Template = template;
                Response = response;
                Kind = kind;
            }

            public string TypeFullName { get; }
            public string TypeName { get; }
            public string Verb { get; }
            public string Template { get; }
            public string Response { get; }
            public HandlerKind Kind { get; }
        }
    }
}
