<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Classification and redaction primitives for compliance-aware applications.</Description>
    <PackageTags>Ark;C#;.NET;Framework;Compliance;Privacy;PII;Redaction</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ark.Tools.Compliance.Generators\Ark.Tools.Compliance.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.Extensions.Compliance.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\Ark.Tools.Compliance.Generators\bin\$(Configuration)\netstandard2.0\Ark.Tools.Compliance.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false"
          Condition="Exists('$(MSBuildThisFileDirectory)..\Ark.Tools.Compliance.Generators\bin\$(Configuration)\netstandard2.0\Ark.Tools.Compliance.Generators.dll')" />
  </ItemGroup>

</Project>
