// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ark.Tools.Compliance.Generators;

/// <summary>Generates deterministic, explicitly mapped SQL policy templates.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SqlPolicyGenerator : IIncrementalGenerator
{
    private const string _dataPolicy = "Ark.Tools.Compliance.Sql.SqlDataPolicyAttribute";
    private const string _columnPolicy = "Ark.Tools.Compliance.Sql.SqlColumnPolicyAttribute";

    private static readonly DiagnosticDescriptor _invalidMapping = new(
        "ARKPII207", "Invalid SQL policy mapping",
        "SQL policy for '{0}' is invalid: {1}", "Compliance", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            _dataPolicy,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol).Collect();
        var enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.EnableArkToolsCompliance", out var value)
            || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase));
        context.RegisterSourceOutput(types.Combine(enabled), static (ctx, input) =>
        {
            var source = new StringBuilder("// <auto-generated/>\n");
            foreach (var type in input.Left.Distinct(SymbolEqualityComparer.Default)
                         .OfType<INamedTypeSymbol>().OrderBy(static t => t.ToDisplayString(), StringComparer.Ordinal))
            {
                if (input.Right)
                {
                    source.Append(_emit(ctx, type));
                }
            }
            ctx.AddSource("ArkComplianceSql.manifest.g.cs", source.ToString());
        });
    }

    private static string _emit(SourceProductionContext context, INamedTypeSymbol type)
    {
        var policy = type.GetAttributes().First(a => a.AttributeClass?.ToDisplayString() == _dataPolicy);
        var columns = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var invalid = false;
        for (var current = type; current is not null; current = current.BaseType)
        {
            foreach (var member in current.GetMembers().Where(static m => !m.IsStatic && !m.IsImplicitlyDeclared
                         && m.Kind is SymbolKind.Property or SymbolKind.Field))
            {
                var mapping = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == _columnPolicy);
                if (mapping is null)
                {
                    continue;
                }

                var schema = _text(mapping, "Schema") ?? _text(policy, "Schema") ?? "$(ComplianceSchema)";
                var table = _text(mapping, "Table") ?? _text(policy, "Table");
                var column = mapping.ConstructorArguments.Length > 0 ? mapping.ConstructorArguments[0].Value as string : null;
                var storage = mapping.ConstructorArguments.Length > 1 ? mapping.ConstructorArguments[1].Value as int? : null;
                var mask = _text(mapping, "MaskFunction") ?? "default()";
                var label = _text(mapping, "Label") ?? _text(policy, "Label") ?? "$(ComplianceLabel)";
                var classification = _classification(member) ?? _classification(_memberType(member)) ?? _classification(type);
                var information = _text(mapping, "InformationType") ?? classification;
                if (!_valid(schema) || !_valid(table) || !_valid(column) || !_valid(label)
                    || storage is null or < 0 or > 2 || (storage == 1 && !_valid(mask))
                    || (information is not null && !_valid(information)))
                {
                    context.ReportDiagnostic(Diagnostic.Create(_invalidMapping, member.Locations.FirstOrDefault(),
                        member.ToDisplayString(), "schema, table, column, label and protection must be explicit and valid single-line values"));
                    invalid = true;
                    continue;
                }

                var target = _identifier(schema!) + "." + _identifier(table!);
                var columnIdentifier = _identifier(column!);
                var key = target + "." + columnIdentifier;
                var sql = new StringBuilder();
                if (information is not null)
                {
                    sql.Append("ADD SENSITIVITY CLASSIFICATION TO ").Append(key)
                        .Append("\n    WITH (LABEL = ").Append(_literal(label))
                        .Append(", INFORMATION_TYPE = ").Append(_literal(information))
                        .Append(", RANK = ").Append(classification is "Secret" or "SensitivePersonalData" ? "CRITICAL" : "HIGH")
                        .Append(");\n");
                }
                if (storage == 1)
                {
                    sql.Append("ALTER TABLE ").Append(target).Append("\n    ALTER COLUMN ").Append(columnIdentifier)
                        .Append(" ADD MASKED WITH (FUNCTION = ").Append(_literal(mask)).Append(");\n");
                }
                if (sql.Length == 0)
                {
                    continue;
                }
                if (columns.ContainsKey(key))
                {
                    context.ReportDiagnostic(Diagnostic.Create(_invalidMapping, member.Locations.FirstOrDefault(),
                        member.ToDisplayString(), "more than one member maps to the same SQL column"));
                    invalid = true;
                }
                else
                {
                    columns.Add(key, sql.ToString());
                }
            }
        }
        if (invalid || columns.Count == 0)
        {
            return string.Empty;
        }

        var template = "-- Generated SQL policy template. Review before deployment; no encryption or keys are provisioned.\n"
            + string.Join("\n", columns.Values);
        var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(template));
        using var hash = SHA256.Create();
        var identity = hash.ComputeHash(Encoding.UTF8.GetBytes(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        var fileName = "policy-" + BitConverter.ToString(identity).Replace("-", string.Empty).ToLowerInvariant() + ".compliance.sql";
        return "// ArkComplianceSqlTemplate:" + fileName + ":" + payload + "\n";
    }

    private static string? _text(AttributeData attribute, string name)
    {
        return attribute.NamedArguments.FirstOrDefault(p => p.Key == name).Value.Value as string;
    }

    private static ITypeSymbol? _memberType(ISymbol member)
    {
        return member is IPropertySymbol property ? property.Type : (member as IFieldSymbol)?.Type;
    }

    private static string? _classification(ISymbol? symbol)
    {
        if (symbol is null)
        {
            return null;
        }
        if (symbol is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            return _classification(nullable.TypeArguments[0]);
        }
        foreach (var name in new[] { "Secret", "SensitivePersonalData", "PersonalData", "Pseudonymous" })
        {
            if (symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Ark.Tools.Compliance." + name + "Attribute"))
            {
                return name;
            }
        }
        if (symbol.GetAttributes().Any(static a => a.AttributeClass?.OriginalDefinition.ToDisplayString()
                == "Ark.Tools.Compliance.SensitiveValueObjectAttribute<T>"))
        {
            return "PersonalData";
        }
        foreach (var attribute in symbol.GetAttributes())
        {
            for (var current = attribute.AttributeClass?.BaseType; current is not null; current = current.BaseType)
            {
                if (current.ToDisplayString() == "Microsoft.Extensions.Compliance.Classification.DataClassificationAttribute")
                {
                    return attribute.AttributeClass!.Name.Replace("Attribute", string.Empty);
                }
            }
        }
        return null;
    }

    private static bool _valid(string? value)
    {
        return !string.IsNullOrWhiteSpace(value) && !value!.Any(char.IsControl);
    }

    private static string _identifier(string value)
    {
        return "[" + value.Replace("]", "]]") + "]";
    }

    private static string _literal(string value)
    {
        return "'" + value.Replace("'", "''") + "'";
    }
}
