// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Ark.Tools.Compliance.Generators;

/// <summary>Generates deterministic, explicitly mapped SQL policy templates.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SqlPolicyGenerator : IIncrementalGenerator
{
    private const string _dataPolicy = "Ark.Tools.Compliance.Sql.SqlDataPolicyAttribute";
    private const string _columnPolicy = "Ark.Tools.Compliance.Sql.SqlColumnPolicyAttribute";

    private static readonly DiagnosticDescriptor _invalidMapping = new(
        "ARKPII207", "Invalid SQL policy mapping",
        "SQL policy for '{0}' is invalid: {1}", "Compliance", DiagnosticSeverity.Error, true, helpLinkUri: "https://github.com/ARKlab/Ark.Tools/blob/master/docs/analyzer-rules/ARKPII207.md");

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            _dataPolicy,
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, token) => _parse(ctx, token))
            .Where(static spec => spec is not null)
            .Select(static (spec, _) => spec!)
            .WithComparer(SqlPolicySpecComparer.Instance)
            .Collect()
            .WithComparer(SqlPolicySpecArrayComparer.Instance);
        var enabled = context.AnalyzerConfigOptionsProvider.Select(static (options, _) =>
            !options.GlobalOptions.TryGetValue("build_property.EnableArkToolsCompliance", out var value)
            || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase));
        context.RegisterSourceOutput(types.Combine(enabled), static (ctx, input) =>
        {
            var source = new StringBuilder("// <auto-generated/>\n");
            foreach (var type in input.Left.OrderBy(static t => t.FullyQualifiedName, StringComparer.Ordinal))
            {
                ctx.CancellationToken.ThrowIfCancellationRequested();
                if (!input.Right)
                {
                    break;
                }

                var result = SqlPolicyGenerator._emit(type);
                foreach (var diagnostic in result.Diagnostics)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        _invalidMapping,
                        diagnostic.Location.ToLocation(),
                        diagnostic.MemberName,
                        diagnostic.Reason));
                }

                if (!result.Invalid)
                {
                    source.Append(result.Template);
                }
            }
            ctx.AddSource("ArkComplianceSql.manifest.g.cs", source.ToString());
        });
    }

    private static SqlPolicySpec? _parse(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (context.TargetSymbol is not INamedTypeSymbol type)
        {
            return null;
        }

        var policy = context.Attributes[0];
        var columns = new List<SqlColumnSpec>();
        var diagnostics = new List<SqlDiagnosticSpec>();
        for (var current = type; current is not null; current = current.BaseType)
        {
            cancellationToken.ThrowIfCancellationRequested();
            foreach (var member in current.GetMembers().Where(static m => !m.IsStatic && !m.IsImplicitlyDeclared
                         && m.Kind is SymbolKind.Property or SymbolKind.Field))
            {
                var mapping = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == _columnPolicy);
                if (mapping is null)
                {
                    continue;
                }

                var schema = _text(mapping, "Schema") ?? _text(policy, "Schema") ?? "$(ComplianceSchema)";
                var table = _text(mapping, "Table") ?? _text(policy, "Table");
                var column = mapping.ConstructorArguments.Length > 0 ? mapping.ConstructorArguments[0].Value as string : null;
                var storage = mapping.ConstructorArguments.Length > 1 ? mapping.ConstructorArguments[1].Value as int? : null;
                var mask = _text(mapping, "MaskFunction") ?? "default()";
                var label = _text(mapping, "Label") ?? _text(policy, "Label") ?? "$(ComplianceLabel)";
                var classification = _classification(member) ?? _classification(_memberType(member)) ?? _classification(type);
                var information = _text(mapping, "InformationType") ?? classification;
                if (!_valid(schema) || !_valid(table) || !_valid(column) || !_valid(label)
                    || storage is null or < 0 or > 2 || (storage == 1 && !_valid(mask))
                    || (information is not null && !_valid(information)))
                {
                    diagnostics.Add(new SqlDiagnosticSpec(
                        LocationSpec.Create(member.Locations.FirstOrDefault()),
                        member.ToDisplayString(),
                        "schema, table, column, label and protection must be explicit and valid single-line values"));
                    continue;
                }

                columns.Add(new SqlColumnSpec(
                    LocationSpec.Create(member.Locations.FirstOrDefault(), member.ToDisplayString()),
                    schema!,
                    table!,
                    column!,
                    storage.Value,
                    mask!,
                    label!,
                    information,
                    classification));
            }
        }

        return new SqlPolicySpec(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            columns.ToImmutableArray(),
            diagnostics.ToImmutableArray());
    }

    private static SqlEmission _emit(SqlPolicySpec type)
    {
        var columns = new SortedDictionary<string, string>(StringComparer.Ordinal);
        var diagnostics = type.Diagnostics.ToBuilder();
        foreach (var member in type.Columns)
        {
            var target = _identifier(member.Schema) + "." + _identifier(member.Table);
            var columnIdentifier = _identifier(member.Column);
            var key = target + "." + columnIdentifier;
            var sql = new StringBuilder();
            if (member.Information is not null)
            {
                sql.Append("ADD SENSITIVITY CLASSIFICATION TO ").Append(key)
                    .Append("\n    WITH (LABEL = ").Append(_literal(member.Label))
                    .Append(", INFORMATION_TYPE = ").Append(_literal(member.Information))
                    .Append(", RANK = ").Append(member.Classification is "UserCredentials" or "InfrastructureSecret" or "Secret" or "SensitivePersonalData" ? "CRITICAL" : "HIGH")
                    .Append(");\n");
            }
            if (member.Storage == 1)
            {
                sql.Append("ALTER TABLE ").Append(target).Append("\n    ALTER COLUMN ").Append(columnIdentifier)
                    .Append(" ADD MASKED WITH (FUNCTION = ").Append(_literal(member.Mask)).Append(");\n");
            }
            if (sql.Length == 0)
            {
                continue;
            }
            if (columns.ContainsKey(key))
            {
                diagnostics.Add(new SqlDiagnosticSpec(
                    member.Location,
                    member.MemberName,
                    "more than one member maps to the same SQL column"));
            }
            else
            {
                columns.Add(key, sql.ToString());
            }
        }
        if (diagnostics.Count > 0 || columns.Count == 0)
        {
            return new SqlEmission(string.Empty, diagnostics.ToImmutable(), diagnostics.Count > 0);
        }

        var template = "-- Generated SQL policy template. Review before deployment; no encryption or keys are provisioned.\n"
            + string.Join("\n", columns.Values);
        var payload = Convert.ToBase64String(Encoding.UTF8.GetBytes(template));
        using var hash = SHA256.Create();
        var identity = hash.ComputeHash(Encoding.UTF8.GetBytes(type.FullyQualifiedName));
        var fileName = "policy-" + BitConverter.ToString(identity).Replace("-", string.Empty).ToLowerInvariant() + ".compliance.sql";
        return new SqlEmission(
            "// ArkComplianceSqlTemplate:" + fileName + ":" + payload + "\n",
            diagnostics.ToImmutable(),
            false);
    }

    private static string? _text(AttributeData attribute, string name)
    {
        return attribute.NamedArguments.FirstOrDefault(p => p.Key == name).Value.Value as string;
    }

    private static ITypeSymbol? _memberType(ISymbol member)
    {
        return member is IPropertySymbol property ? property.Type : (member as IFieldSymbol)?.Type;
    }

    private static string? _classification(ISymbol? symbol)
    {
        if (symbol is null)
        {
            return null;
        }
        if (symbol is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
        {
            return _classification(nullable.TypeArguments[0]);
        }
        foreach (var name in new[] { "Secret", "SensitivePersonalData", "PersonalData", "Pseudonymous" })
        {
            if (symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "Ark.Tools.Compliance." + name + "Attribute"))
            {
                return name;
            }
        }
        if (symbol.GetAttributes().Any(static a => a.AttributeClass?.OriginalDefinition.ToDisplayString()
                == "Ark.Tools.Compliance.SensitiveValueObjectAttribute<T>"))
        {
            return "PersonalData";
        }
        foreach (var attribute in symbol.GetAttributes())
        {
            for (var current = attribute.AttributeClass?.BaseType; current is not null; current = current.BaseType)
            {
                if (current.ToDisplayString() == "Microsoft.Extensions.Compliance.Classification.DataClassificationAttribute")
                {
                    return attribute.AttributeClass!.Name.Replace("Attribute", string.Empty);
                }
            }
        }
        return null;
    }

    private static bool _valid(string? value)
    {
        return !string.IsNullOrWhiteSpace(value) && !value!.Any(char.IsControl);
    }

    private static string _identifier(string value)
    {
        return "[" + value.Replace("]", "]]") + "]";
    }

    private static string _literal(string value)
    {
        return "'" + value.Replace("'", "''") + "'";
    }

    private sealed record SqlPolicySpec(
        string FullyQualifiedName,
        ImmutableArray<SqlColumnSpec> Columns,
        ImmutableArray<SqlDiagnosticSpec> Diagnostics);

    private readonly record struct SqlColumnSpec(
        LocationSpec Location,
        string Schema,
        string Table,
        string Column,
        int Storage,
        string Mask,
        string Label,
        string? Information,
        string? Classification)
    {
        internal string MemberName => Location.MemberName;
    }

    private readonly record struct SqlDiagnosticSpec(
        LocationSpec Location,
        string MemberName,
        string Reason);

    private readonly record struct SqlEmission(
        string Template,
        ImmutableArray<SqlDiagnosticSpec> Diagnostics,
        bool Invalid);

    private readonly record struct LocationSpec(
        string FilePath,
        int Start,
        int Length,
        int StartLine,
        int StartCharacter,
        int EndLine,
        int EndCharacter,
        string MemberName = "")
    {
        internal static LocationSpec Create(Location? location, string memberName = "")
        {
            if (location is null || !location.IsInSource)
            {
                return new LocationSpec(string.Empty, 0, 0, 0, 0, 0, 0, memberName);
            }

            var lineSpan = location.GetLineSpan().Span;
            return new LocationSpec(
                location.SourceTree?.FilePath ?? string.Empty,
                location.SourceSpan.Start,
                location.SourceSpan.Length,
                lineSpan.Start.Line,
                lineSpan.Start.Character,
                lineSpan.End.Line,
                lineSpan.End.Character,
                memberName);
        }

        internal Location ToLocation()
        {
            return string.IsNullOrEmpty(FilePath)
                ? Location.None
                : Location.Create(
                    FilePath,
                    new TextSpan(Start, Length),
                    new LinePositionSpan(
                        new LinePosition(StartLine, StartCharacter),
                        new LinePosition(EndLine, EndCharacter)));
        }
    }

    private sealed class SqlPolicySpecComparer : IEqualityComparer<SqlPolicySpec>
    {
        internal static readonly SqlPolicySpecComparer Instance = new();

        public bool Equals(SqlPolicySpec? x, SqlPolicySpec? y)
        {
            return ReferenceEquals(x, y)
                || (x is not null && y is not null
                    && string.Equals(x.FullyQualifiedName, y.FullyQualifiedName, StringComparison.Ordinal)
                    && x.Columns.SequenceEqual(y.Columns)
                    && x.Diagnostics.SequenceEqual(y.Diagnostics));
        }

        public int GetHashCode(SqlPolicySpec obj)
        {
            var hash = StringComparer.Ordinal.GetHashCode(obj.FullyQualifiedName);
            foreach (var column in obj.Columns)
            {
                hash = unchecked((hash * 397) ^ column.GetHashCode());
            }

            foreach (var diagnostic in obj.Diagnostics)
            {
                hash = unchecked((hash * 397) ^ diagnostic.GetHashCode());
            }

            return hash;
        }
    }

    private sealed class SqlPolicySpecArrayComparer : IEqualityComparer<ImmutableArray<SqlPolicySpec>>
    {
        internal static readonly SqlPolicySpecArrayComparer Instance = new();

        public bool Equals(ImmutableArray<SqlPolicySpec> x, ImmutableArray<SqlPolicySpec> y)
        {
            return x.SequenceEqual(y, SqlPolicySpecComparer.Instance);
        }

        public int GetHashCode(ImmutableArray<SqlPolicySpec> obj)
        {
            var hash = 17;
            foreach (var spec in obj)
            {
                hash = unchecked((hash * 397) ^ SqlPolicySpecComparer.Instance.GetHashCode(spec));
            }

            return hash;
        }
    }
}
