// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

using Ark.Tools.MediatorFramework.Generators;

using Microsoft.CodeAnalysis;

using static Ark.Tools.MediatorFramework.AzureFunctions.Generators.MessagingFunctionsNaming;

namespace Ark.Tools.MediatorFramework.AzureFunctions.Generators;

/// <summary>Generates Azure Functions messaging triggers and desired-resource manifests.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class MessagingFunctionsGenerator : IIncrementalGenerator
{
    private const string _hostAttribute =
        "Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsHostAttribute";
    private const string _hostAttributeStage = "MessagingFunctionsHostAttributes";
    private const string _hostSpecStage = "MessagingFunctionsHostSpecs";
    private const string _hostJsonStage = "MessagingFunctionsHostJson";
    private const string _specStage = "MessagingFunctionsSpecs";
    private const string _outputStage = "MessagingFunctionsOutput";
    private const int _serviceBusBinding = 0;
    private const int _storageQueueBinding = 1;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hosts = context.SyntaxProvider.ForAttributeWithMetadataName(
                _hostAttribute,
                static (_, _) => true,
                static (attributeContext, cancellationToken) =>
                    MessagingFunctionsParser._readHosts(attributeContext, cancellationToken))
            .WithTrackingName(_hostAttributeStage)
            .SelectMany(static (extracted, _) => extracted)
            .WithTrackingName(_hostSpecStage)
            .Collect();
        var hostJson = context.AdditionalTextsProvider
            .Where(static text => string.Equals(
                Path.GetFileName(text.Path),
                "host.json",
                StringComparison.OrdinalIgnoreCase))
            .Select(static (text, cancellationToken) =>
                text.GetText(cancellationToken)?.ToString())
            .WithTrackingName(_hostJsonStage)
            .Collect();
        var specs = hosts.Combine(hostJson)
            .Select(static (pair, _) => new MessagingFunctionsAggregateSpec(
                pair.Left
                    .OrderBy(static host => host.ParticipantTypeName, StringComparer.Ordinal)
                    .ThenBy(static host => host.Binding)
                    .ToImmutableArray(),
                pair.Right
                    .OrderBy(static content => content ?? string.Empty, StringComparer.Ordinal)
                    .ToImmutableArray()))
            .WithTrackingName(_specStage);
        var output = specs
            .Select(static (spec, _) => spec)
            .WithTrackingName(_outputStage);

        context.RegisterSourceOutput(
            output,
            static (productionContext, spec) =>
                _emit(productionContext, spec.Hosts.Values, spec.HostJson.Values));
    }

    private static void _emit(
        SourceProductionContext context,
        ImmutableArray<MessagingHostSpec> hosts,
        ImmutableArray<string?> hostJson)
    {
        if (hosts.IsDefaultOrEmpty)
            return;

        var ordered = hosts
            .OrderBy(static host => host.ParticipantTypeName, StringComparer.Ordinal)
            .ThenBy(static host => host.Binding)
            .ToImmutableArray();
        if (ordered.Length != 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MessagingFunctionsDiagnostics._multipleHosts,
                LocationSpec._toLocation(ordered[0].Location)));
            return;
        }

        var host = ordered[0];
        foreach (var diagnostic in host.ParseDiagnostics)
            context.ReportDiagnostic(diagnostic._toDiagnostic(MessagingFunctionsDiagnostics._descriptor));

        if (host.ValidateHostJson)
            _validateHostJson(context, host, hostJson);

        foreach (var diagnostic in host.TopologyDiagnostics)
            context.ReportDiagnostic(diagnostic._toDiagnostic(MessagingFunctionsDiagnostics._descriptor));

        if (!host.IsEmittable)
            return;

        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("namespace Ark.Tools.MediatorFramework.AzureFunctions.Generated;")
            .AppendLine()
            .AppendLine("public sealed class ArkGeneratedMessagingFunctions : global::Ark.Tools.MediatorFramework.AzureFunctions.IMessagingFunctionsHost<ArkGeneratedMessagingFunctions>")
            .AppendLine("{");

        _emitManifest(source, host);

        if (!host.SenderOnly)
            _emitTrigger(source, host.Binding, host.Identity, host.Connection);

        source.AppendLine("}");
        context.AddSource("ArkGeneratedMessagingFunctions.g.cs", source._toGeneratedSource());
    }

    private static void _emitManifest(StringBuilder source, in MessagingHostSpec host)
    {
        var retryType = host.RetryTypeName;
        source.AppendLine("    /// <summary>Gets the deterministic desired-resource manifest for this messaging host.</summary>")
            .AppendLine("    public static global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsManifest Manifest { get; } =")
            .AppendLine("        new global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsManifest(")
            .Append("            typeof(").Append(host.ParticipantTypeName).AppendLine("),")
            .Append("            typeof(").Append(host.NetworkTypeName).AppendLine("),")
            .Append("            ").Append(host.ParticipantTypeName).Append(".CreateDescriptor(")
            .Append(host.NetworkTypeName).Append(".CreateOptions(), ")
            .Append(host.NetworkTypeName).AppendLine(".Registry),")
            .Append("            global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsTriggerBinding.")
            .AppendLine(host.Binding == _serviceBusBinding ? "ServiceBus," : "StorageQueue,")
            .Append("            \"").Append(_escape(_nativeName(host.Identity, host.Binding))).AppendLine("\",")
            .Append("            \"").Append(_escape(host.Connection)).AppendLine("\",");

        _emitMaximumDeliveryCount(source, retryType, "            ", appendComma: true);
        source.AppendLine();
        source.Append(retryType is null
                ? "            global::System.TimeSpan.FromMinutes(5),"
                : "            new " + retryType + "().MaximumHandlerDuration,")
            .AppendLine();

        source.AppendLine("            new global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsSubscription[]")
            .AppendLine("            {");
        foreach (var subscription in host.Subscriptions)
        {
            source.AppendLine("                new global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsSubscription(")
                .Append("                    \"").Append(_escape(_nativeName(subscription.Topic, host.Binding))).AppendLine("\",")
                .Append("                    \"").Append(_escape(_nativeName(subscription.Name, host.Binding))).AppendLine("\",")
                .Append("                    \"").Append(_escape(_nativeName(subscription.ForwardToQueue, host.Binding))).AppendLine("\"),");
        }

        source.AppendLine("            },");
        _emitTypes(source, host.IncomingSteps);
        source.AppendLine(",");
        _emitTypes(source, host.OutgoingSteps);
        source.AppendLine(",");
        if (retryType is null)
            source.AppendLine("            global::System.TimeSpan.Zero,");
        else
            source.Append("            new ").Append(retryType).AppendLine("().RetryDelay,");
        source.Append("            ").Append(host.StrictStorageQueueHostSettings ? "true" : "false")
            .AppendLine(",")
            .AppendLine("            new global::Ark.Tools.MediatorFramework.Messaging.MessagingResourceManifest(")
            .Append("                \"").Append(_escape(host.Identity)).AppendLine("\",")
            .Append("                ").Append(host.HasIdentityQueue ? "\"" + _escape(host.Identity) + "\"" : "null")
            .AppendLine(",");
        _emitMaximumDeliveryCount(source, retryType, "                ", appendComma: true);
        source.AppendLine()
            .AppendLine("                new global::Ark.Tools.MediatorFramework.Messaging.MessagingTopicResource[]")
            .AppendLine("                {");
        foreach (var topic in host.DesiredTopics.Values.OrderBy(static topic => topic.Name, StringComparer.Ordinal))
        {
            source.AppendLine("                    new global::Ark.Tools.MediatorFramework.Messaging.MessagingTopicResource(")
                .Append("                        \"").Append(_escape(topic.Name)).AppendLine("\",")
                .Append("                        \"").Append(_escape(topic.OwnerIdentity)).AppendLine("\"),");
        }
        source.AppendLine("                },")
            .AppendLine("                new global::Ark.Tools.MediatorFramework.Messaging.MessagingSubscriptionResource[]")
            .AppendLine("                {");
        foreach (var subscription in host.Subscriptions)
        {
            source.AppendLine("                    new global::Ark.Tools.MediatorFramework.Messaging.MessagingSubscriptionResource(")
                .Append("                        \"").Append(_escape(subscription.Topic)).AppendLine("\",")
                .Append("                        \"").Append(_escape(subscription.Name)).AppendLine("\",")
                .Append("                        \"").Append(_escape(subscription.ForwardToQueue)).AppendLine("\",");
            _emitMaximumDeliveryCount(source, retryType, "                        ", appendComma: true);
            source.AppendLine()
                .Append("                        \"").Append(_escape(host.Identity)).AppendLine("\"),");
        }
        source.AppendLine("                },")
            .AppendLine("                new string[]")
            .AppendLine("                {");
        foreach (var topic in host.KnownTopics.Values.OrderBy(static topic => topic.Name, StringComparer.Ordinal))
            source.Append("                    \"").Append(_escape(topic.Name)).AppendLine("\",");
        source.AppendLine("                },")
            .Append("                (global::Ark.Tools.MediatorFramework.MessagingResourceLifecycle)")
            .Append(host.ResourceLifecycleText).AppendLine("),")
            .Append("            ")
            .Append(host.ManagedIdentityConfigurationKey is null
                ? "null"
                : "\"" + _escape(host.ManagedIdentityConfigurationKey) + "\"")
            .AppendLine(");")
            .AppendLine();
    }

    private static void _emitMaximumDeliveryCount(
        StringBuilder source,
        string? retryTypeName,
        string indentation,
        bool appendComma)
    {
        source.Append(indentation);
        if (retryTypeName is null)
        {
            source.Append('1');
        }
        else
        {
            source.Append("checked(new ").Append(retryTypeName)
                .Append("().MaximumDeliveryCount * (new ").Append(retryTypeName)
                .Append("().SecondLevelRetriesEnabled ? 2 : 1))");
        }
        if (appendComma)
            source.Append(',');
    }

    private static void _emitTypes(StringBuilder source, EquatableArray<string> typeNames)
    {
        source.AppendLine("            new global::System.Type[]")
            .AppendLine("            {");
        foreach (var typeName in typeNames)
            source.Append("                typeof(").Append(typeName).AppendLine("),");
        source.Append("            }");
    }

    private static void _emitTrigger(
        StringBuilder source,
        int binding,
        string identity,
        string connection)
    {
        var methodName = _functionName(identity);
        var nativeIdentity = _nativeName(identity, binding == _storageQueueBinding ? 63 : 260,
            binding == _storageQueueBinding);
        source.Append("    /// <summary>Receives the \"").Append(_escape(identity))
            .AppendLine("\" participant identity queue.</summary>")
            .Append("    [global::Microsoft.Azure.Functions.Worker.Function(\"")
            .Append(_escape(identity)).AppendLine("\")]")
            .Append("    public static async global::System.Threading.Tasks.Task ")
            .Append(methodName).AppendLine("(");
        if (binding == _serviceBusBinding)
        {
            source.AppendLine("        [global::Microsoft.Azure.Functions.Worker.ServiceBusTrigger(")
                .Append("            \"").Append(_escape(nativeIdentity)).AppendLine("\",")
                .Append("            Connection = \"").Append(_escape(connection)).AppendLine("\",")
                .AppendLine("            AutoCompleteMessages = false)]")
                .AppendLine("        global::Azure.Messaging.ServiceBus.ServiceBusReceivedMessage message,")
                .AppendLine("        global::Microsoft.Azure.Functions.Worker.ServiceBusMessageActions messageActions,")
                .AppendLine("        global::Microsoft.Azure.Functions.Worker.FunctionContext functionContext,")
                .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
                .AppendLine("    {")
                .AppendLine("        await global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingFunctionsDispatcher")
                .AppendLine("            .DispatchAsync(message, messageActions, functionContext, cancellationToken)")
                .AppendLine("            .ConfigureAwait(false);")
                .AppendLine("    }");
            return;
        }

        source.AppendLine("        [global::Microsoft.Azure.Functions.Worker.QueueTrigger(")
            .Append("            \"").Append(_escape(nativeIdentity)).AppendLine("\",")
            .Append("            Connection = \"").Append(_escape(connection)).AppendLine("\")]")
            .AppendLine("        global::Azure.Storage.Queues.Models.QueueMessage message,")
            .AppendLine("        global::Microsoft.Azure.Functions.Worker.FunctionContext functionContext,")
            .AppendLine("        global::System.Threading.CancellationToken cancellationToken)")
            .AppendLine("    {")
            .AppendLine("        await global::Ark.Tools.MediatorFramework.AzureFunctions.MessagingQueueFunctionsDispatcher")
            .Append("            .DispatchAsync(message, \"").Append(_escape(identity))
            .AppendLine("\", functionContext, cancellationToken)")
            .AppendLine("            .ConfigureAwait(false);")
            .AppendLine("    }");
    }

    private static void _validateHostJson(
        SourceProductionContext context,
        in MessagingHostSpec host,
        ImmutableArray<string?> hostJson)
    {
        var location = LocationSpec._toLocation(host.Location);
        var content = hostJson.FirstOrDefault(static value => value is not null);
        if (content is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(MessagingFunctionsDiagnostics._hostJsonNotInspectable, location));
            return;
        }

        // ponytail: Build-time checks inspect three fixed literal properties; use a JSON parser
        // if the host contract grows beyond this flat Functions queues settings object.
        if (!_regexIsMatch(
                content,
                "\"messageEncoding\"\\s*:\\s*\"none\""))
        {
            context.ReportDiagnostic(Diagnostic.Create(MessagingFunctionsDiagnostics._invalidMessageEncoding, location));
        }
        if (!_regexIsMatch(
                content,
                "\"maxDequeueCount\"\\s*:\\s*[1-9][0-9]*"))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MessagingFunctionsDiagnostics._invalidMaximumDequeueCount,
                location));
        }

        var visibility = Regex.Match(
            content,
            "\"visibilityTimeout\"\\s*:\\s*\"(?<value>[^\"]+)\"",
            RegexOptions.CultureInvariant,
            TimeSpan.FromSeconds(1));
        if (!visibility.Success
            || !TimeSpan.TryParse(
                visibility.Groups["value"].Value,
                CultureInfo.InvariantCulture,
                out var delay)
            || delay <= TimeSpan.Zero)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MessagingFunctionsDiagnostics._invalidVisibilityTimeout,
                location));
        }
    }

    private static bool _regexIsMatch(string value, string pattern)
    {
        return Regex.IsMatch(
            value,
            pattern,
            RegexOptions.CultureInvariant,
            TimeSpan.FromSeconds(1));
    }

    private sealed record MessagingFunctionsAggregateSpec(
        EquatableArray<MessagingHostSpec> Hosts,
        EquatableArray<string?> HostJson);
}
