// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;

namespace Ark.MediatorFramework.AzureFunctions.Generators;

/// <summary>Discovers messaging network declarations for generated host metadata.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class MessagingNetworkGenerator : IIncrementalGenerator
{
    private const string _attributeName = "Ark.MediatorFramework.MessagingNetworkAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var networks = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                _attributeName,
                static (_, _) => true,
                static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol)
            .Collect();

        context.RegisterSourceOutput(networks, static (productionContext, symbols) =>
        {
            foreach (var symbol in symbols
                .Distinct(SymbolEqualityComparer.Default)
                .OrderBy(symbol => symbol.ToDisplayString(), StringComparer.Ordinal))
            {
                var identity = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .Replace("global::", string.Empty);
                var hint = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                    .Replace(".", "_");
                var source = new StringBuilder()
                    .AppendLine("// <auto-generated />")
                    .Append("namespace Ark.MediatorFramework.Generated;")
                    .AppendLine()
                    .Append("internal static class ").Append(hint).Append("MessagingNetwork")
                    .AppendLine()
                    .AppendLine("{")
                    .Append("    internal const string Identity = \"").Append(identity.Replace("\"", "\\\"")).AppendLine("\";")
                    .AppendLine("}")
                    .ToString();
                productionContext.AddSource(hint + ".MessagingNetwork.g.cs", source);
            }
        });
    }
}
