<Project Sdk="Microsoft.NET.Sdk">

  <!-- the other props are defined in Directory.Build.props -->
  <!--===================Configuration for Nuget Package=========================-->
  <PropertyGroup>

    <Description>Newtonsoft.Json converters for Ark.Tools.Compliance sensitive value objects</Description>
    <PackageTags>Ark;C#;.NET;Framework;Compliance;Privacy;PII;Json;NewtonsoftJson</PackageTags>

    <!--Update these information when releasing a new version of the NugetPackage-->
    <PackageReleaseNotes></PackageReleaseNotes>

    <!-- Trimming configuration -->
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>

  <!--===============================================================================-->
  <ItemGroup>
    <ProjectReference Include="..\Ark.Tools.Compliance\Ark.Tools.Compliance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>
