<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <EnableArkToolsCompliance>false</EnableArkToolsCompliance>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Ark.Tools.Compliance" />
    <PackageReference Include="Ark.Tools.Compliance.Sql" />
    <ProjectReference Include="..\..\Ark.Reference.Common\Ark.Reference.Common.csproj" />
  </ItemGroup>

</Project>
