<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageId>Ark.Tools.Sdk</PackageId>
    <Description>Ark.Tools additional MSBuild SDK.</Description>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <!-- NU5128 is expected because this package intentionally contains only MSBuild assets. -->
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <IncludeSymbols>false</IncludeSymbols>
    <GenerateSBOM>false</GenerateSBOM>
    <ArkToolsSdkProject>true</ArkToolsSdkProject>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Sdk\Sdk.targets" Pack="true" PackagePath="Sdk/Sdk.targets" />
    <None Include="$(IntermediateOutputPath)Sdk.props" Pack="true" PackagePath="Sdk/Sdk.props" />
  </ItemGroup>

  <Target Name="GenerateSdkProps" BeforeTargets="GenerateNuspec">
    <Copy SourceFiles="Sdk\Sdk.props" DestinationFiles="$(IntermediateOutputPath)Sdk.props" />
    <XmlPoke
      XmlInputPath="$(IntermediateOutputPath)Sdk.props"
      Query="/Project/ItemGroup/PackageReference[@Include='Ark.Tools.Build']/@Version"
      Value="$(PackageVersion)" />
  </Target>
</Project>
