syntax = "proto3";

option csharp_namespace = "Ark.MediatorFramework.Sample.GrpcClient";

import "google/type/date.proto";
import "google/type/datetime.proto";
import "google/protobuf/empty.proto";
import "ark/mediator.proto";

message DownloadDocumentMetadata {
  string name = 1;
  string content_type = 2;
  optional int64 length = 3;
}

message DownloadDocumentChunk {
  oneof content {
    DownloadDocumentMetadata metadata = 1;
    bytes data = 2;
  }
}

message UploadBatchResponse {
  bytes id = 1;
  repeated string names = 2;
}

message UploadResponse {
  bytes id = 1;
  string name = 2;
  string content_type = 3;
  int64 length = 4;
}

service DocumentsV1 {
  rpc GetDocument(bytes) returns (stream DownloadDocumentChunk);
  rpc UploadGreetingCard(stream ark.mediator.UploadDocumentChunk) returns (UploadResponse);
  rpc UploadGreetingCards(stream ark.mediator.UploadDocumentChunk) returns (UploadBatchResponse);
}

