// Copyright (C) 2024 Ark Energy S.r.l. All rights reserved.
// Licensed under the MIT License. See LICENSE file for license information.

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ark.Tools.Solid.SimpleInjector.Generators;

/// <summary>
/// Generates strongly typed SimpleInjector dispatch for statically discoverable Solid handlers.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SolidSimpleInjectorDispatcherGenerator : IIncrementalGenerator
{
    private const string RequestHandler = "Ark.Tools.Solid.IRequestHandler";
    private const string QueryHandler = "Ark.Tools.Solid.IQueryHandler";
    private const string CommandHandler = "Ark.Tools.Solid.ICommandHandler";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider.Select(static (compilation, _) => CreateSource(compilation)),
            static (productionContext, source) =>
            {
                if (source.Length != 0)
                    productionContext.AddSource("SolidSimpleInjectorDispatcher.g.cs", source);
            });
    }

    private static string CreateSource(Compilation compilation)
    {
        var requests = new SortedSet<DispatchEntry>(DispatchEntryComparer.Instance);
        var queries = new SortedSet<DispatchEntry>(DispatchEntryComparer.Instance);
        var commands = new SortedSet<DispatchEntry>(DispatchEntryComparer.Instance);

        foreach (var type in GetTypes(compilation.Assembly.GlobalNamespace))
        {
            foreach (var handler in type.AllInterfaces)
            {
                if (handler.TypeArguments.Length == 0)
                {
                    continue;
                }

                var definition = handler.OriginalDefinition.ContainingNamespace.ToDisplayString()
                    + "." + handler.OriginalDefinition.MetadataName;
                if (definition == RequestHandler && handler.TypeArguments.Length == 2)
                    requests.Add(new DispatchEntry(handler.TypeArguments[0], handler.TypeArguments[1], handler));
                else if (definition == QueryHandler && handler.TypeArguments.Length == 2)
                    queries.Add(new DispatchEntry(handler.TypeArguments[0], handler.TypeArguments[1], handler));
                else if (definition == CommandHandler && handler.TypeArguments.Length == 1)
                    commands.Add(new DispatchEntry(handler.TypeArguments[0], result: null, handler));
            }
        }

        if (requests.Count == 0 && queries.Count == 0 && commands.Count == 0)
            return string.Empty;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Ark.Tools.Solid.SimpleInjector.Generated;");
        source.AppendLine();
        source.AppendLine("internal static class SolidSimpleInjectorGeneratedInitializer");
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.AppendLine("    internal static void Initialize()");
        source.AppendLine("    {");
        source.AppendLine("        global::Ark.Tools.Solid.SimpleInjector.SolidSimpleInjectorDispatchRegistry.Current = new SolidSimpleInjectorGeneratedDispatcher();");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("/// <summary>Generated dispatch for statically discoverable Solid handlers.</summary>");
        source.AppendLine("public sealed class SolidSimpleInjectorGeneratedDispatcher : global::Ark.Tools.Solid.SimpleInjector.ISolidSimpleInjectorDispatcher");
        source.AppendLine("{");
        AppendRequestMethod(source, requests);
        AppendQueryMethod(source, queries);
        AppendCommandMethod(source, commands);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendRequestMethod(StringBuilder source, IEnumerable<DispatchEntry> entries)
    {
        source.AppendLine("    public bool TryExecuteRequest<TResponse>(");
        source.AppendLine("        global::SimpleInjector.Container container,");
        source.AppendLine("        global::Ark.Tools.Solid.IRequest<TResponse> request,");
        source.AppendLine("        global::System.Threading.CancellationToken ctk,");
        source.AppendLine("        out global::System.Threading.Tasks.Task<TResponse>? execution)");
        source.AppendLine("    {");
        foreach (var entry in entries)
        {
            source.Append("        if (request is ").Append(TypeName(entry.Message)).AppendLine(" typedRequest)");
            source.AppendLine("        {");
            source.Append("            execution = container.GetInstance<global::Ark.Tools.Solid.IRequestHandler<")
                .Append(TypeName(entry.Message)).Append(", ").Append(TypeName(entry.Result!)).AppendLine(">>().ExecuteAsync(typedRequest, ctk);");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        execution = null;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void AppendQueryMethod(StringBuilder source, IEnumerable<DispatchEntry> entries)
    {
        source.AppendLine("    public bool TryExecuteQuery<TResult>(");
        source.AppendLine("        global::SimpleInjector.Container container,");
        source.AppendLine("        global::Ark.Tools.Solid.IQuery<TResult> query,");
        source.AppendLine("        global::System.Threading.CancellationToken ctk,");
        source.AppendLine("        out global::System.Threading.Tasks.Task<TResult>? execution)");
        source.AppendLine("    {");
        foreach (var entry in entries)
        {
            source.Append("        if (query is ").Append(TypeName(entry.Message)).AppendLine(" typedQuery)");
            source.AppendLine("        {");
            source.Append("            execution = container.GetInstance<global::Ark.Tools.Solid.IQueryHandler<")
                .Append(TypeName(entry.Message)).Append(", ").Append(TypeName(entry.Result!)).AppendLine(">>().ExecuteAsync(typedQuery, ctk);");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        execution = null;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void AppendCommandMethod(StringBuilder source, IEnumerable<DispatchEntry> entries)
    {
        source.AppendLine("    public bool TryExecuteCommand(");
        source.AppendLine("        global::SimpleInjector.Container container,");
        source.AppendLine("        global::Ark.Tools.Solid.ICommand command,");
        source.AppendLine("        global::System.Threading.CancellationToken ctk,");
        source.AppendLine("        out global::System.Threading.Tasks.Task? execution)");
        source.AppendLine("    {");
        foreach (var entry in entries)
        {
            source.Append("        if (command is ").Append(TypeName(entry.Message)).AppendLine(" typedCommand)");
            source.AppendLine("        {");
            source.Append("            execution = container.GetInstance<global::Ark.Tools.Solid.ICommandHandler<")
                .Append(TypeName(entry.Message)).AppendLine(">>().ExecuteAsync(typedCommand, ctk);");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }

        source.AppendLine("        execution = null;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
    }

    private static string TypeName(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static IEnumerable<INamedTypeSymbol> GetTypes(INamespaceSymbol @namespace)
    {
        foreach (var member in @namespace.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
            {
                foreach (var type in GetTypes(childNamespace))
                    yield return type;
            }
            else if (member is INamedTypeSymbol type)
            {
                yield return type;
                foreach (var nestedType in GetNestedTypes(type))
                    yield return nestedType;
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetNestedTypes(INamedTypeSymbol type)
    {
        foreach (var nestedType in type.GetTypeMembers())
        {
            yield return nestedType;
            foreach (var childType in GetNestedTypes(nestedType))
                yield return childType;
        }
    }

    private sealed class DispatchEntry
    {
        public DispatchEntry(ITypeSymbol message, ITypeSymbol? result, INamedTypeSymbol handler)
        {
            Message = message;
            Result = result;
            Handler = handler;
        }

        public ITypeSymbol Message { get; }
        public ITypeSymbol? Result { get; }
        public INamedTypeSymbol Handler { get; }
    }

    private sealed class DispatchEntryComparer : IComparer<DispatchEntry>
    {
        public static DispatchEntryComparer Instance { get; } = new();

        public int Compare(DispatchEntry? x, DispatchEntry? y)
        {
            if (ReferenceEquals(x, y))
                return 0;
            if (x is null)
                return -1;
            if (y is null)
                return 1;

            var messageComparison = StringComparer.Ordinal.Compare(TypeName(x.Message), TypeName(y.Message));
            if (messageComparison != 0)
                return messageComparison;
            return StringComparer.Ordinal.Compare(
                x.Result is null ? string.Empty : TypeName(x.Result),
                y.Result is null ? string.Empty : TypeName(y.Result));
        }
    }
}
