CREATE TABLE [dbo].[Audit]
(
    [AuditId]   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[UserId]  NVARCHAR(255) NOT NULL,
	[Kind]    NVARCHAR(255) NOT NULL,
	[Info]      NVARCHAR(max) NULL,
	
    [SysStartTime] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [SysEndTime] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,  
	PERIOD FOR SYSTEM_TIME ([SysStartTime], [SysEndTime]),

    CONSTRAINT [Audit_PK] PRIMARY KEY CLUSTERED ([AuditId] ASC)
)
WITH    
   (   
      SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[AuditHistory]),
	  DATA_COMPRESSION = PAGE
   )

