<!-- The Ark.Tools.Build version is replaced with the package version by GenerateSdkProps. -->
<Project>
  <Import Project="../../Ark.Tools.Build/build/Ark.Tools.Build.common.props"
          Condition="'$(_ArkToolsSdkSourceBuild)' == 'true'" />

  <Import Project="$(MSBuildThisFileDirectory)../common/common.props" Condition="'$(EnableArkToolsBuild)' != 'false'" />

</Project>
