<Project Sdk="Microsoft.NET.Sdk">

  <!-- the other props are defined in Directory.Build.props -->
  <!--===================Configuration for Nuget Package=========================-->
  <PropertyGroup>

    <Description>MessagePack formatter resolver for Ark.Tools.Core.EvolvableEnum, always carrying the numeric wire value</Description>
    <PackageTags>Ark;C#;.NET;Framework;MessagePack;Enum</PackageTags>

    <!--Update these information when releasing a new version of the NugetPackage-->
    <PackageReleaseNotes></PackageReleaseNotes>

    <Version>$(ArkToolsCoreVersion)</Version>
    <VersionSuffix>$(ArkToolsCoreVersionSuffix)</VersionSuffix>

    <Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version>
  </PropertyGroup>
  <!--===============================================================================-->

  <ItemGroup>
    <ProjectReference Include="..\Ark.Tools.Core\Ark.Tools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
  </ItemGroup>

</Project>
