name: 'Dependency Review'
on: [pull_request]

permissions:
  id-token: write
  contents: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: 'Build'
        run: dotnet build --configuration Release
      - name: Generate SBOM
        run: | 
            curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
            chmod +x $RUNNER_TEMP/sbom-tool
            $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn ${{ github.repository }} -pv 1.0.0 -ps OwnerName -nsb https://sbom.mycompany.com -V Verbose
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: _manifest/spdx_2.2
      - name: SBOM upload 
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
        with:
          filePath: "_manifest/spdx_2.2/"        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Use comma-separated names to pass list arguments:
          allow-licenses: MIT,Apache-2.0,BSD-3-Clause,BSD-2-Clause
  