name: 'Dependency Review'
on: [pull_request]

permissions:
  id-token: write
  contents: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: 'Build'
        run: dotnet build --configuration Release
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Use comma-separated names to pass list arguments:
          allow-licenses: MIT,Apache-2.0,BSD-3-Clause,BSD-2-Clause
  